package Acme::CPANLists::Import::PerlAdvent::2004;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2004/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"DateTime"},{module=>"DateTime::Duration"},{module=>"DateTime::Format::Duration"},{module=>"DateTime::Format::HTTP"},{module=>"Acme::Colour"},{module=>"Term::ANSIColor"},{module=>"Term::Cap"},{module=>"Class::Accessor"},{module=>"Class::Accessor::Chained"},{module=>"String::ShellQuote"},{module=>"CPAN::Mini"},{module=>"Imager"},{module=>"Module::Pluggable"},{module=>"Module::Pluggable::Ordered"},{module=>"LWP::Parallel"},{module=>"LWP::Simple"},{module=>"Term::ProgressBar"},{module=>"Data::Dumper"},{module=>"Data::Dumper::Simple"},{module=>"Email::Address"},{module=>"Email::Simple"},{module=>"File::Copy"},{module=>"Proc::Daemon"},{module=>"Proc::PID::File"},{module=>"Data::UUID"},{module=>"Tie::DataUUID"},{module=>"Encode"},{module=>"Text::Unidecode"},{module=>"Devel::Trace"},{module=>"Class::DBI"},{module=>"DBI"},{module=>"SQL::Abstract"},{module=>"Archive::Extract"},{module=>"File::Temp"},{module=>"Cache::Cache"},{module=>"Cache::FastMemoryCache"},{module=>"Cache::FileCache"},{module=>"Cache::MemoryCache"},{module=>"Cache::SharedMemoryCache"},{module=>"Mac::Glue"},{module=>"Acme::Drunk"},{module=>"Filesys::Virtual"},{module=>"Filesys::Virtual::DAAP"},{module=>"Filesys::Virtual::Plain"},{module=>"Filesys::Virtual::SSH"},{module=>"HTTP::Daemon"},{module=>"Net::DAV::Server"},{module=>"POE::Component::Server::FTP"},{module=>"Sys::Hostname"}],summary=>"Modules mentioned in Perl Advent Calendar 2004"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2004

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2004/> (retrieved on 2016-11-07). Visit the URL for the full contents.

