package Acme::CPANLists::Import::PerlAdvent::2004_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2004/20th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Filesys::Virtual"},{module=>"Filesys::Virtual::DAAP"},{module=>"Filesys::Virtual::Plain"},{module=>"Filesys::Virtual::SSH"},{module=>"HTTP::Daemon"},{module=>"Net::DAV::Server"},{module=>"POE::Component::Server::FTP"}],summary=>"Modules mentioned in Perl Advent Calendar 2004 (day 20)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2004 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2004/20th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

