package Acme::CPANLists::Import::PerlAdvent::2004_12_13;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2004/13th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Devel::Trace"}],summary=>"Modules mentioned in Perl Advent Calendar 2004 (day 13)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2004 (day 13)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2004/13th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

