#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2004',
                url => "http://perladvent.org/2004/",
                extract_urls => [map {"http://perladvent.org/2004/$_/"}
                             qw(1st 2nd 3rd 4th 5th 6th 7th 8th 9th 10th 11th 12th 13th 14th 15th 16th 17th 18th 19th 20th 21st 22nd 23rd 24th 25th)],
                summary => 'Modules mentioned in Perl Advent Calendar 2004',
            },
            {
                name => '2004_12_01',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 1)",
                url => "http://perladvent.org/2004/1st/",
            },
            {
                name => '2004_12_02',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 2)",
                url => "http://perladvent.org/2004/2nd/",
            },
            {
                name => '2004_12_03',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 3)",
                url => "http://perladvent.org/2004/3rd/",
            },
            {
                name => '2004_12_04',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 4)",
                url => "http://perladvent.org/2004/4th/",
            },
            {
                name => '2004_12_05',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 5)",
                url => "http://perladvent.org/2004/5th/",
            },
            {
                name => '2004_12_06',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 6)",
                url => "http://perladvent.org/2004/6th/",
                add_modules => ['App::XLSperl'],
            },
            {
                name => '2004_12_07',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 7)",
                url => "http://perladvent.org/2004/7th/",
            },
            {
                name => '2004_12_08',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 8)",
                url => "http://perladvent.org/2004/8th/",
            },
            {
                name => '2004_12_09',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 9)",
                url => "http://perladvent.org/2004/9th/",
            },
            {
                name => '2004_12_10',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 10)",
                url => "http://perladvent.org/2004/10th/",
            },
            {
                name => '2004_12_11',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 11)",
                url => "http://perladvent.org/2004/11th/",
            },
            {
                name => '2004_12_12',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 12)",
                url => "http://perladvent.org/2004/12th/",
            },
            {
                name => '2004_12_13',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 13)",
                url => "http://perladvent.org/2004/13th/",
            },
            {
                name => '2004_12_14',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 14)",
                url => "http://perladvent.org/2004/14th/",
            },
            {
                name => '2004_12_15',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 15)",
                url => "http://perladvent.org/2004/15th/",
            },
            {
                name => '2004_12_16',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 16)",
                url => "http://perladvent.org/2004/16th/",
            },
            {
                name => '2004_12_17',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 17)",
                url => "http://perladvent.org/2004/17th/",
            },
            {
                name => '2004_12_18',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 18)",
                url => "http://perladvent.org/2004/18th/",
            },
            {
                name => '2004_12_20',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 20)",
                url => "http://perladvent.org/2004/20th/",
            },
            {
                name => '2004_12_21',
                summary => "Modules mentioned in Perl Advent Calendar 2004 (day 21)",
                url => "http://perladvent.org/2004/21st/",
            },
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
